### ISSUE TITLE
Push countries to ratify UN treaties

### ISSUE THREAD

**Issue by klengbratveit** [DataForGood-Norway/project-ideas#6]
1. Scrape https://treaties.un.org/Pages/ParticipationStatus.aspx?clang=_en
2. Make applications. For example twitter bot for anniversary ...include naming countries not still ratified

**Comment by Patechoc** [comment]
Great idea!

It didn't look to complex to implement until I looked for countries not compliant in one case, e.g. "chap.4 Human Rights". China signed it in 1949 like many countries, but ratified much later in 1983 **with reservations**:

> "Reservation:
>        2.	The People's Republic of China does not consider itself bound by article IX of the said Convention."

Article 9 is just about...

"Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment.   New York, 10 December 1984".

That makes the app a bit more challenging ;P

**Comment by klengbratveit** [comment]
We could leave out the reservations in the first solution.

**Comment by klengbratveit** [comment]
The idea is to make attention to the Treaties, not be the monitor it all...

**Comment by klengbratveit** [comment]
I have talked to head of Treaty section in UN today: UN experts: https://vimeo.com/162124950

Here is some of what he said:
- They have no formal obligation to communicate status of treaties to the general public
- Still they were one of the first UN organizations to make a website. This is made by lawyers, to solve their need.
- There is an inhouse database for Treaties, but this is also their documentation tool. There is no API availeble of their Treaty database. 
- Newer documents are in full text. Old Treaties are in scanned PDFs!
- Other UN bodies would very much like to promote signing and ratification of their treaties.
- We have a need for better registering incomming data. Now states can only send paper documents.
- We are responsible for Treaty Event every year inviting states to sign / ratify new treaties.
----> Lets have a conference call with Data4Good and my technical team!!

**Comment by dhesse** [comment]
Started on the crawling code today. [It's here](https://github.com/DataForGood-Norway/ResoCrawl).

**Comment by klengbratveit** [comment]
For the "Treaty-anniversary-twitter-bot" we will probably need the variables; 
Name of treaty, 
Date of treaty,
Date of entry into force,
Participants, with:
Date of signature,
Date of acceptence,
Date of ratification

**Comment by klengbratveit** [comment]
Some comments:
- The titles of some of the Treaty is not self-explanatory (Leave this for now)
- Some treaties are not put in to force jet. It may be interesting to be able to analyze data to see what treaties only need one more signature, etc. I did not find a easy variable to tell how individual treaties are put into force. It is explained in the scanned pdf of the law:(
- Some odd treaties, not in force, have been signed by "remote" countries - maybe only to let the heads of state visit UN or why? Example Benin: https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVIII-1&chapter=28&clang=_en

**Comment by Patechoc** [comment]
Now the project started and you can join it by contributong to this repository: https://github.com/DataForGood-Norway/ResoCrawl
